FROM envoyproxy/envoy:latest
ENV HOME /root

RUN apt-get update && apt-get install -y ca-certificates openssl iptables curl emacs nmap telnet

# from https://hub.docker.com/r/albodor/mysql-shell/~/dockerfile/
RUN set -x \
 && apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https wget libprotobuf9v5 libpython2.7 python \
 && rm -rf /var/lib/apt/lists/*

RUN wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell_1.0.11-1ubuntu16.04_amd64.deb \
 && DEBIAN_FRONTEND=noninteractive dpkg -i ./mysql-shell_1.0.11-1ubuntu16.04_amd64.deb \
 && rm -f ./mysql-shell_1.0.11-1ubuntu16.04_amd64.deb


RUN useradd -ms /bin/bash clientuser

WORKDIR $HOME
COPY set_iptables.sh $HOME
COPY run_envoy.sh $HOME
COPY .cache/bazel/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy_filter_example/bazel-out/k8-fastbuild/bin/envoy /usr/local/bin/envoy
COPY envoy_config.json $HOME/envoy_config.json

# expose envoy's stasd port
EXPOSE 8001